use super::*;

pub(super) const LIFESTYLE_PATTERNS: &[QuerySurfacePattern] = &[
    // ── Vehicle / Car model ──────────────────────────────────────────────────
    (
        &[
            "i drive",
            "my car is",
            "bought a car",
            "new car",
            "my truck",
            "my suv",
            "my motorcycle",
            "my bike",
            "leased a",
            "test drove",
        ],
        &[
            "what car does she drive",
            "what vehicle does he own",
            "what kind of car",
            "does she have a car",
            "car",
            "vehicle",
            "drive",
            "model",
            "yes",
        ],
    ),
    // ── Diet / Food preferences ──────────────────────────────────────────────
    (
        &[
            "i'm vegan",
            "i'm vegetarian",
            "i eat ",
            "my diet",
            "i don't eat",
            "gluten free",
            "lactose",
            "i avoid",
            "food allergy",
            "i'm allergic to",
            "i'm pescatarian",
            "i'm keto",
            "low carb",
        ],
        &[
            "what does she eat",
            "is she vegan",
            "what is his diet",
            "food preferences",
            "diet",
            "vegan",
            "vegetarian",
            "gluten",
            "allergy",
            "food",
        ],
    ),
    // ── Language spoken ──────────────────────────────────────────────────────
    (
        &[
            "i speak",
            "i'm fluent",
            "my native language",
            "i'm learning",
            "i know french",
            "i know spanish",
            "i know german",
            "i know japanese",
            "i know chinese",
            "i know arabic",
            "i know italian",
            "bilingual",
            "multilingual",
        ],
        &[
            "what language does she speak",
            "what languages does he know",
            "is she bilingual",
            "language",
            "speak",
            "fluent",
            "native",
        ],
    ),
    // ── Religion / Faith ─────────────────────────────────────────────────────
    (
        &[
            "i'm christian",
            "i'm muslim",
            "i'm jewish",
            "i'm buddhist",
            "i'm hindu",
            "my religion",
            "my faith",
            "i pray",
            "i go to church",
            "i go to mosque",
            "i'm catholic",
            "i'm atheist",
            "i'm agnostic",
            "my beliefs",
        ],
        &[
            "what religion does she follow",
            "is he religious",
            "what faith",
            "religion",
            "faith",
            "church",
            "pray",
            "belief",
        ],
    ),
    // ── Sport / Physical activity ────────────────────────────────────────────
    (
        &[
            "i play soccer",
            "i play football",
            "i play basketball",
            "i play tennis",
            "i play golf",
            "i play baseball",
            "i play volleyball",
            "i play rugby",
            "i go swimming",
            "i go cycling",
            "i go running",
            "i go hiking",
            "my team",
            "i coach",
            "i train",
            "i compete",
            "my sport",
        ],
        &[
            "what sport does she play",
            "what sport does he play",
            "what team",
            "sport",
            "team",
            "play",
            "compete",
            "athletic",
        ],
    ),
    // ── Musical instrument ───────────────────────────────────────────────────
    (
        &[
            "i play guitar",
            "i play piano",
            "i play violin",
            "i play drums",
            "i play bass",
            "i play flute",
            "i play saxophone",
            "i play trumpet",
            "i play cello",
            "i play ukulele",
            "my instrument",
            "i'm in a band",
        ],
        &[
            "what instrument does she play",
            "does he play an instrument",
            "does she play music",
            "instrument",
            "music",
            "band",
            "guitar",
            "piano",
        ],
    ),
    // ── Social media / Online presence ───────────────────────────────────────
    (
        &[
            "my instagram",
            "my twitter",
            "my tiktok",
            "my youtube",
            "my twitch",
            "my linkedin",
            "my handle",
            "my username",
            "i post on",
            "my followers",
            "my channel",
            "my blog",
            "my podcast",
            "my newsletter",
        ],
        &[
            "what is her instagram",
            "what is his twitter",
            "social media",
            "instagram",
            "twitter",
            "youtube",
            "tiktok",
            "handle",
            "channel",
            "followers",
            "platform",
            "subscribers",
            "views",
            "online",
        ],
    ),
    // ── Subscription / Membership ────────────────────────────────────────────
    (
        &[
            "i subscribe",
            "my subscription",
            "i'm a member",
            "my membership",
            "i pay for",
            "i cancelled",
            "netflix",
            "spotify",
            "gym membership",
        ],
        &[
            "does she have a subscription",
            "what subscriptions",
            "membership",
            "subscribe",
            "service",
            "member",
            "yes",
        ],
    ),
    // ── Medication / Prescription ────────────────────────────────────────────
    (
        &[
            "i take ",
            "my medication",
            "my prescription",
            "i'm on ",
            "my pills",
            "my dosage",
            "i was prescribed",
            "my antidepressant",
            "my antibiotic",
        ],
        &[
            "what medication does she take",
            "is he on medication",
            "prescription",
            "medication",
            "medicine",
            "pills",
            "prescription",
            "dosage",
        ],
    ),
    // ── Marital status change ────────────────────────────────────────────────
    (
        &[
            "i got divorced",
            "going through a divorce",
            "we separated",
            "i'm separated",
            "signed divorce papers",
            "legally separated",
            "my ex",
            "my ex-husband",
            "my ex-wife",
            "divorced now",
        ],
        &[
            "is she divorced",
            "is he separated",
            "relationship status",
            "divorced",
            "separated",
            "divorce",
            "ex",
            "single",
            "no",
        ],
    ),
    // ── New home / Moving ────────────────────────────────────────────────────
    (
        &[
            "i'm moving",
            "we're moving",
            "just moved",
            "new apartment",
            "new house",
            "new home",
            "bought a house",
            "renting",
            "my new place",
            "signed a lease",
        ],
        &[
            "did she move",
            "where did he move",
            "new address",
            "moved",
            "new home",
            "address",
            "house",
            "apartment",
            "neighborhood",
        ],
    ),
    // ── Travel / Country visited ─────────────────────────────────────────────
    (
        &[
            "i visited",
            "i went to",
            "i traveled to",
            "i'm going to",
            "my trip",
            "my vacation",
            "my holiday",
            "i'm in ",
            "just got back from",
            "i flew to",
            "i drove to",
            "i'm visiting",
        ],
        &[
            "where did she travel",
            "what countries has he visited",
            "travel plans",
            "trip",
            "vacation",
            "travel",
            "visit",
            "country",
            "destination",
        ],
    ),
    // ── Named colleague / coworker ───────────────────────────────────────────
    (
        &[
            "my boss",
            "my manager",
            "my colleague",
            "my coworker",
            "my supervisor",
            "my team lead",
            "my mentor",
            "my intern",
            "works with me",
            "my teammate",
        ],
        &[
            "who is her boss",
            "who does she work with",
            "coworker",
            "colleague",
            "boss",
            "manager",
            "supervisor",
            "team",
            "work relationship",
        ],
    ),
];
