use super::*;

pub(super) const PERSONAL_PATTERNS: &[QuerySurfacePattern] = &[
    (
        &[
            "i'm from",
            "i grew up in",
            "my home country",
            "my hometown",
            "originally from",
            "i was raised in",
            "my nationality",
            "i'm american",
            "i'm british",
            "i'm australian",
            "i'm canadian",
            "i'm french",
            "i'm german",
            "i'm italian",
            "i'm japanese",
            "i'm korean",
            "i'm chinese",
            "i'm indian",
            "i'm brazilian",
            "i'm mexican",
        ],
        &[
            "where is she from",
            "what is his nationality",
            "what country",
            "nationality",
            "origin",
            "hometown",
            "country",
            "from",
        ],
    ),
    // ── Gym / Workout routine ────────────────────────────────────────────────
    (
        &[
            "i go to the gym",
            "i work out",
            "my workout",
            "my fitness routine",
            "i lift weights",
            "i do yoga",
            "i do pilates",
            "i do crossfit",
            "my personal trainer",
            "i exercise",
        ],
        &[
            "does she go to the gym",
            "what is his workout routine",
            "fitness",
            "gym",
            "workout",
            "exercise",
            "fitness routine",
            "training",
            "yes",
        ],
    ),
    // ── Sports team / Fan ────────────────────────────────────────────────────
    (
        &[
            "i'm a fan of",
            "i support",
            "my favorite team",
            "my team is",
            "i cheer for",
            "i root for",
        ],
        &[
            "what team does she support",
            "favorite sports team",
            "fan",
            "team",
            "support",
            "cheer",
        ],
    ),
    // ── Allergies ────────────────────────────────────────────────────────────
    (
        &[
            "i'm allergic",
            "my allergy",
            "allergic to",
            "i can't eat",
            "i react to",
            "my epipen",
            "anaphylactic",
            "nut allergy",
            "shellfish allergy",
        ],
        &[
            "what is she allergic to",
            "does he have allergies",
            "allergy",
            "allergic",
            "reaction",
            "food allergy",
        ],
    ),
    // ── Volunteering / Charity ───────────────────────────────────────────────
    (
        &[
            "i volunteer",
            "i volunteer at",
            "my volunteer work",
            "i donate",
            "i work with a charity",
            "nonprofit",
            "community service",
        ],
        &[
            "does she volunteer",
            "what charity does he support",
            "volunteering",
            "volunteer",
            "charity",
            "donate",
            "nonprofit",
        ],
    ),
    // ── Graduation / Degree completion ───────────────────────────────────────
    (
        &[
            "i graduated",
            "i finished my degree",
            "i got my degree",
            "just graduated",
            "got my phd",
            "got my masters",
            "got my bachelors",
            "commencement",
        ],
        &[
            "when did she graduate",
            "what degree did he get",
            "graduated",
            "graduation",
            "degree",
            "diploma",
            "alumni",
        ],
    ),
    // ── Job promotion / Title change ─────────────────────────────────────────
    (
        &[
            "i got promoted",
            "i was promoted",
            "i'm now a",
            "new title",
            "senior now",
            "my new role",
            "i lead",
            "i manage now",
            "team lead now",
        ],
        &[
            "was she promoted",
            "what is his new title",
            "promotion",
            "promoted",
            "title",
            "role",
            "senior",
            "lead",
        ],
    ),
    // ── Birth year / Generation ──────────────────────────────────────────────
    (
        &[
            "i was born in",
            "born in 19",
            "born in 20",
            "class of",
            "generation",
            "millennial",
            "gen z",
            "gen x",
            "boomer",
        ],
        &[
            "what year was she born",
            "how old is he",
            "birth year",
            "generation",
            "born",
            "age",
            "millennial",
        ],
    ),
    // ── Salary / Compensation ────────────────────────────────────────────────
    (
        &[
            "my salary is",
            "i make ",
            "i earn ",
            "i get paid",
            "annual salary",
            "hourly rate",
            "i got a raise",
            "my compensation",
            "base salary",
        ],
        &[
            "what is her salary",
            "how much does he earn",
            "salary",
            "income",
            "earn",
            "pay",
            "compensation",
            "raise",
        ],
    ),
    // ── Pregnancy / Child update ─────────────────────────────────────────────
    (
        &[
            "i'm pregnant",
            "we're expecting",
            "due in",
            "my baby is due",
            "i gave birth",
            "our new baby",
            "newborn",
            "just had a baby",
        ],
        &[
            "is she pregnant",
            "when is she due",
            "did she have the baby",
            "pregnant",
            "expecting",
            "due date",
            "baby",
            "newborn",
        ],
    ),
    // ── Social preference / Introvert / Extrovert ────────────────────────────
    (
        &[
            "i'm an introvert",
            "i'm an extrovert",
            "i prefer small gatherings",
            "i love parties",
            "i avoid crowds",
            "i'm shy",
            "i'm outgoing",
            "i socialize",
            "i like to be alone",
        ],
        &[
            "is she introverted",
            "is he outgoing",
            "social preference",
            "introvert",
            "extrovert",
            "social",
            "personality",
        ],
    ),
    // ── Time zone / Schedule ─────────────────────────────────────────────────
    (
        &[
            "my time zone",
            "i'm in pst",
            "i'm in est",
            "i'm in gmt",
            "i'm in cet",
            "i work nights",
            "night shift",
            "morning shift",
            "i work remotely",
            "i work from home",
            "wfh",
            "my schedule",
        ],
        &[
            "what time zone is she in",
            "what is his schedule",
            "time zone",
            "schedule",
            "shift",
            "remote",
            "work from home",
        ],
    ),
    // ── Named pet (with name) ────────────────────────────────────────────────
    (
        &[
            "my dog named",
            "my cat named",
            "my pet named",
            "called my dog",
            "called my cat",
            "my dog's name is",
            "my cat's name is",
        ],
        &[
            "what is her pet's name",
            "what is his dog's name",
            "what is the cat called",
            "pet name",
            "dog name",
            "cat name",
        ],
    ),
    // ── Subscription service preference ──────────────────────────────────────
    (
        &[
            "i use ",
            "i prefer ",
            "my favorite app",
            "my go-to",
            "i rely on",
            "i switched from",
            "i switched to",
            "i unsubscribed",
        ],
        &[
            "what app does she use",
            "what service does he prefer",
            "preferred service",
            "app",
            "service",
            "use",
            "prefer",
            "favorite",
        ],
    ),
];
