use super::*;

pub(super) const BASIC_PATTERNS: &[QuerySurfacePattern] = &[
    // ── Occupation / Job ────────────────────────────────────────────────────────
    (
        &[
            "work as",
            "works as",
            "i am a ",
            "i'm a ",
            "i am an ",
            "i'm an ",
            "my job",
            "my career",
            "my profession",
            "my occupation",
            "became a ",
            "got a job",
            "started as",
            "employed as",
            "hired as",
            "nurse",
            "doctor",
            "engineer",
            "teacher",
            "manager",
            "developer",
            "lawyer",
            "accountant",
            "designer",
            "analyst",
            "scientist",
            "therapist",
            "firefighter",
            "police",
            "chef",
            "pilot",
            "architect",
            "consultant",
            "hospital shift",
            "hospital ward",
            "patients were",
            "seeing patients",
            "office job",
            "remote job",
            "full-time",
            "part-time",
            "freelance",
        ],
        &[
            "what is her job",
            "what does she do",
            "what is her occupation",
            "what is her profession",
            "what does she work as",
            "what is his job",
            "what does he do",
            "what is his occupation",
            "what is their job",
            "what is her career",
            "what is her work",
            "what does she do for work",
            "where does she work",
            "job",
            "occupation",
            "profession",
            "career",
            "work",
        ],
    ),
    // ── Location / Residence ─────────────────────────────────────────────────
    (
        &[
            "i live",
            "i moved",
            "i'm living",
            "i am living",
            "my home is",
            "my house",
            "my apartment",
            "my place",
            "relocated to",
            "settled in",
            "based in",
            "moving to",
            "new city",
            "new town",
            "new place",
        ],
        &[
            "where does she live",
            "where does he live",
            "where do they live",
            "what city does she live in",
            "where is her home",
            "where did she move",
            "what is her address",
            "where is she based",
            "location",
            "city",
            "home",
            "residence",
        ],
    ),
    // ── Relationship / Partner ───────────────────────────────────────────────
    (
        &[
            "my husband",
            "my wife",
            "my partner",
            "my spouse",
            "my boyfriend",
            "my girlfriend",
            "my fiance",
            "we got married",
            "getting married",
            "our wedding",
            "we're engaged",
            "i'm engaged",
            "i'm married",
        ],
        &[
            "is she married",
            "who is her husband",
            "who is her partner",
            "who is her spouse",
            "what is her relationship status",
            "is he married",
            "who is his wife",
            "who is their partner",
            "relationship",
            "married",
            "husband",
            "wife",
            "partner",
            "spouse",
            "engaged",
            "yes",
        ],
    ),
    // ── Children / Family ────────────────────────────────────────────────────
    (
        &[
            "my daughter",
            "my son",
            "my kids",
            "my children",
            "my baby",
            "my child",
            "pregnant",
            "expecting",
            "gave birth",
            "new baby",
            "i have a ",
            "we have a kid",
            "we have children",
        ],
        &[
            "does she have children",
            "does he have kids",
            "how many children",
            "does she have a daughter",
            "does he have a son",
            "children",
            "kids",
            "daughter",
            "son",
            "baby",
            "family",
            "parent",
            "yes",
        ],
    ),
    // ── Contact / Phone ──────────────────────────────────────────────────────
    (
        &[
            "my phone",
            "my number",
            "my mobile",
            "my cell",
            "phone number",
            "contact number",
            "changed my number",
            "new number",
            "new phone",
        ],
        &[
            "what is her phone number",
            "what is his number",
            "what is their phone",
            "how do i contact",
            "what is her contact",
            "phone",
            "number",
            "mobile",
            "cell",
            "contact",
        ],
    ),
    // ── Email / Address ──────────────────────────────────────────────────────
    (
        &[
            "my email",
            "new email",
            "email address",
            "my address",
            "i can be reached",
            "reach me at",
        ],
        &[
            "what is her email",
            "what is his email",
            "what is their email",
            "how to contact",
            "email",
            "address",
            "contact",
        ],
    ),
    // ── Age / Birthday ───────────────────────────────────────────────────────
    (
        &[
            "my birthday",
            "born in",
            "born on",
            "i turned",
            "i'm turning",
            "i am ",
            "years old",
            "i was born",
        ],
        &[
            "how old is she",
            "how old is he",
            "what is her age",
            "when is her birthday",
            "when was she born",
            "age",
            "birthday",
            "born",
            "years old",
        ],
    ),
    // ── Health / Medical ─────────────────────────────────────────────────────
    (
        &[
            "i was diagnosed",
            "i have been sick",
            "my condition",
            "my illness",
            "my surgery",
            "i had surgery",
            "in the hospital",
            "hospital stay",
            "my health",
            "my medication",
            "my treatment",
            "recovering from",
            "chronic",
            "my therapy",
            "health issues",
            "had a bad case of",
            "came down with",
            "dealing with health",
            "health problem",
            "i had a bad case",
            "turned out to be more serious",
        ],
        &[
            "what health issues",
            "is she sick",
            "what condition does she have",
            "what health issue did i have",
            "what illness did i have",
            "what did i have",
            "what was i diagnosed with",
            "medical health illness condition surgery hospital treatment health issue",
        ],
    ),
    // ── Education / School ───────────────────────────────────────────────────
    (
        &[
            "i graduated",
            "i'm studying",
            "i am studying",
            "my degree",
            "my major",
            "i'm in school",
            "i'm in college",
            "i'm at university",
            "going back to school",
            "my thesis",
            "my dissertation",
            "i got accepted",
        ],
        &[
            "what does she study",
            "what is her degree",
            "where does she go to school",
            "what is his major",
            "education",
            "school",
            "college",
            "university",
            "degree",
            "studying",
            "graduated",
        ],
    ),
    // ── Pet ──────────────────────────────────────────────────────────────────
    (
        &[
            "my dog",
            "my cat",
            "my pet",
            "my puppy",
            "my kitten",
            "got a dog",
            "got a cat",
            "adopted a",
        ],
        &[
            "does she have a pet",
            "what kind of pet",
            "what is the pet's name",
            "what breed is her dog",
            "what kind of dog does she have",
            "pet",
            "dog",
            "cat",
            "animal",
            "breed",
            "purebred",
            "yes",
        ],
    ),
    // ── Knowledge-update: "changed to" / "now X" ────────────────────────────
    (
        &[
            "changed to",
            "switched to",
            "now i",
            "now she",
            "now he",
            "updated to",
            "new job",
            "new role",
            "new position",
            "promoted",
            "just started",
            "recently started",
            "just got",
        ],
        &[
            "what changed",
            "what is the current",
            "what is the latest",
            "what is her current",
            "what is his current",
            "current",
            "latest",
            "updated",
            "changed",
            "new",
            "now",
        ],
    ),
    // ── Hobbies / Interests ──────────────────────────────────────────────────
    (
        &[
            "i love",
            "i enjoy",
            "my hobby",
            "i like to",
            "i play",
            "i run",
            "i paint",
            "i write",
            "i sing",
            "i dance",
            "i practice",
            "my passion",
            "my interest",
        ],
        &[
            "what does she enjoy",
            "what are her hobbies",
            "what does she do for fun",
            "hobby",
            "interest",
            "passion",
            "enjoy",
            "like",
        ],
    ),
    // ── Property / Vehicle ───────────────────────────────────────────────────
    (
        &[
            "my car",
            "my house",
            "my apartment",
            "i bought a",
            "i own a",
            "my property",
            "my condo",
            "my vehicle",
        ],
        &[
            "does she own a car",
            "what kind of car",
            "does she own a house",
            "car",
            "house",
            "property",
            "vehicle",
            "apartment",
            "yes",
        ],
    ),
    // ── Financial ───────────────────────────────────────────────────────────
    (
        &[
            "my salary",
            "my income",
            "my savings",
            "i earn",
            "i make",
            "got a raise",
            "my budget",
            "financially",
            "debt",
            "mortgage",
        ],
        &[
            "what is her salary",
            "how much does she make",
            "financial situation",
            "salary",
            "income",
            "money",
            "earnings",
        ],
    ),
];
